# Generated by Django 4.2.3 on 2023-07-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jitter', '0006_meeme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
