# Generated by Django 4.2.3 on 2023-07-16 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jitter', '0007_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeme',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='meeme_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
